<?php

////////////////////////////////////////////////////////////////////////////////////////////////////////
require './vendor/autoload.php'; // This Autoload Generated By Composer
//////////////////////////////////////////////////////////////////////////////////////////////////////////
// ↓↓↓↓↓↓↓↓↓↓  IF YOU WANT TO USE THE MANUAL AUTOLOAD YOU MUST TO DECOMMENT THE SECTION DOWN ↓↓↓↓↓↓↓↓↓↓ //
//require './Manually_Autoload.php'; // This Our Basic Manually Autoload
//Autoload::register();
//////////////////////////////////////////////////////////////////////////////////////////////////////////

// Use NameSpaces
use App\Control\Person;
use App\Module\Person as PersonInformations; // Create Alias To Avoid conflicts Between Two Classes With The Same Name
use App\Module\Voiture;

$person = new Person("Jawad Boulmal",21,"jawadoulmal@gmail.com");
$Voiture = new Voiture("Black","Mercedes");

PersonInformations::AllInformations(
    $person->getName(),
    $Voiture->getModel(),
    $Voiture->getColor()
);
